### ISSUE TITLE
Make a design to contain caption on top of photo as an overlay

### ISSUE THREAD

**Issue by anushas-dev** [anushas-dev/photo-gallery-customizations#4]
Given a photo album of 15 or more images, design a gallery view to showcase them on landing page.

- Captions would not be more than 1 line.
- You have freedom to pick your color palette on dark / bright images.
- Captions are preferred in the bottom, on top of the image, below image show for representation:

![image](https://user-images.githubusercontent.com/95580494/197918559-2f755e9b-507f-4dda-acfc-6abf1921d1e8.png)

##Steps to contribute
- Fork this repo.
- Add your images and designs in a new folder (with your name preferably) under assets folder.
- Also create a README.md file for your folder describing why your design will best suit for gallery view according to you.
- Submit your PR

Thank you.

**Comment by william-monroy** [comment]
Hi @anushas-dev, could you assign me this issue and give me more details about the requirements.

**Comment by anushas-dev** [comment]
> Hi @anushas-dev, could you assign me this issue and give me more details about the requirements.

@william-monroy thank you for your interest, I've updated the details to the issue. Feel free to design something of your interest, no strict requirements.

**Comment by anushas-dev** [comment]
Great work @william-monroy, thank you for your contribution!

**Comment by william-monroy** [comment]
Thanks @anushas-dev, could you add the `hacktoberfest-accepted` label please?
